### PR TITLE
GPU Branch Creation

### PR DESCRIPTION
**Pull request by Kolleida**
# Summary

Created a branch called "gpu" for developing the code for porting the training to GPU. Added the code for reading the data into NVTabular and creating the PyTorch data loader. Both are 1-1 replacements for their non GPU counterparts.

# Things Added

- A GPU version of main.py, called gpu_main.py under e2e_system/
- A folder called e2e_system/gputils/, which will contain the GPU related code
    - Code added in preproc.py

### CODE REVIEW

**Comment by Kolleida** [comment]
Tbh, I made this pull request accidentally, but I guess there would be no problems if it were merged, so what do you guys think?

**Comment by lesleychou** [comment]
Thank you Eric! One question, is the continuous and catagorical column transformation part still slow? Or did you replace it?

**Comment by Kolleida** [comment]
> Thank you Eric! One question, is the continuous and catagorical column transformation part still slow? Or did you replace it? @Kolleida

I haven't replaced the categorical transformation yet, but there seems to be an out of box transform for one hot encoding on GPUs, and I think it's compatible with Dask, so I can get that working. Certain data preprocessing transforms should be possible as long as they can be computed with pandas like operations, so maybe GMM is possible, but I'm not familiar with the math for that.

**Comment by lesleychou** [comment]
> > Thank you Eric! One question, is the continuous and catagorical column transformation part still slow? Or did you replace it? @Kolleida
> 
> I haven't replaced the categorical transformation yet, but there seems to be an out of box transform for one hot encoding on GPUs, and I think it's compatible with Dask, so I can get that working. Certain data preprocessing transforms should be possible as long as they can be computed with pandas like operations, so maybe GMM is possible, but I'm not familiar with the math for that.

Sounds good, merging the PR

**Pull request merged**
